package pkg


const (
	LARK_DOC_TITLE_BANNER_QUESTIONAIRE = "Questionnaire"

	LARK_IM_CARD_ACTION_APPROVE = "approve"
	LARK_IM_CARD_ACTION_DISAPPROVE = "disapprove"

	BANNER_STATUS_PENDING = "pending"
	BANNER_STATUS_APPROVED = "approved"
	BANNER_STATUS_DISAPPROVED = "disapproved"

	LARK_BITABLE_RECORD_ACTION_ADD = "record_added"
	LARK_BITABLE_RECORD_ACTION_EDITED = "record_edited"
	LARK_BITABLE_RECORD_ACTION_DELETE = "record_deleted"
)
